### ISSUE TITLE
docs have wrong install command

### ISSUE THREAD

**Issue by ezpuzz** [concordnow/ember-content-loader#42]
https://concordnow.github.io/ember-content-loader/docs/usage

command here does not work, 404s

**Comment by ctjhoa** [comment]
Good catch! Thanks for the issue.

**Comment by ctjhoa** [comment]
This is fixed on `master`.
https://concordnow.github.io/ember-content-loader/versions/master/docs/usage

I don't want to release a new version only for documentation so it will be finalize in next release.
